[tox]
platform = linux2|darwin

envlist = py37

[testenv]
commands =
				 coverage run --parallel-mode tests/pbPlist_test.py
				;  coverage run --parallel-mode setup.py test

deps =
    coverage
    unittest-xml-reporting
    setuptools
